import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const sample=JSON.parse(readFileSync('public/demo/anime.json','utf8')).map((a:{id:number})=>({...a,coverImage:{large:`/demo/${a.id}-cover.jpg`}}));
test('rate an unsaved anime from its detail, change half-stars and clear after reload',async({page})=>{
 await page.route('https://graphql.anilist.co',route=>route.fulfill({json:{data:{Page:{media:sample,pageInfo:{hasNextPage:false}}}}}));
 await page.goto('/');
 await page.getByRole('button',{name:'Discover',exact:true}).click();
 await page.getByRole('button',{name:'Open Cowboy Bebop',exact:true}).click();
 const hero=page.locator('.detail-hero');
 await expect(hero.getByRole('button',{name:'Rate 3.5 stars',exact:true})).toBeVisible();
 await hero.getByRole('button',{name:'Rate 3.5 stars',exact:true}).click();
 await expect(hero.locator('.stars')).toHaveAttribute('aria-valuenow','3.5');
 await page.mouse.move(0,0);
 await expect(hero.locator('.rating-number')).toHaveText('3.5');
 await hero.getByRole('button',{name:'Rate 4 stars',exact:true}).click();
 await expect(hero.locator('.stars')).toHaveAttribute('aria-valuenow','4');
 await hero.locator('.stars').focus();
 await page.keyboard.press('ArrowLeft');
 await expect(hero.locator('.stars')).toHaveAttribute('aria-valuenow','3.5');
 await page.mouse.move(0,0);
 await page.reload();
 await page.getByRole('button',{name:'Discover',exact:true}).click();
 await page.getByRole('button',{name:'Open Cowboy Bebop',exact:true}).click();
 await expect(hero.locator('.stars')).toHaveAttribute('aria-valuenow','3.5');
 await hero.getByRole('button',{name:'Clear rating',exact:true}).click();
 await page.mouse.move(0,0);
 await expect(hero.locator('.rating-number')).toHaveText('—');
});
