CREATE TEMP TABLE incoming_entries (id TEXT PRIMARY KEY NOT NULL, anilist_id INTEGER NOT NULL UNIQUE, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_lists (id TEXT PRIMARY KEY NOT NULL, public_id TEXT NOT NULL UNIQUE, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_members (list_id TEXT NOT NULL, entry_id TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY(list_id, entry_id), UNIQUE(list_id, position));
CREATE TEMP TABLE incoming_history (id TEXT PRIMARY KEY NOT NULL, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_queue (id TEXT PRIMARY KEY NOT NULL, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_profile (id TEXT PRIMARY KEY NOT NULL, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_preferences (key TEXT PRIMARY KEY NOT NULL, data TEXT NOT NULL);
CREATE TEMP TABLE incoming_search (id INTEGER PRIMARY KEY, data TEXT NOT NULL);
